name: 'Deploy Sanity to Plesk with SSH'

description: 'Deploy to plesk using SSH, copy and backup previous build, deploy the new one, if anything fails rollback to previous one.'

inputs:
  host:
    description: 'SSH Host address or IP'
    required: true
    default: 'None'

  username:
    description: 'SSH Username'
    required: true
    default: 'None'

  key:
    description: 'SSH Private Key'
    required: true
    default: 'None'

  passphrase:
    description: 'SSH Key passphrase'
    required: true
    default: 'None'

  port:
    description: 'SSH Port'
    required: true
    default: 'None'

  source:
    description: 'Paths to files you want to copy seperated with a comma (,)'
    required: true
    default: 'dist/**,deployment/sanity/.htaccess'

  deploy-path:
    description: 'Deploy path in the host. Containing the system location where we want to deploy the build.'
    required: true
    default: 'None'

runs:
  using: 'composite'

  steps:
    - name: 🕒 Current Time
      id: current-time
      shell: bash
      run: echo "now=$(date -u +%Y-%m-%dT%H-%M-%S-%N)" >> $GITHUB_OUTPUT

    - name: ⚙️ Generate MD5 Hash
      id: generate-md5-hash
      shell: bash
      run: |
        echo "md5-hash=$(echo -n ${{ github.ref_name }}-${{ github.event.pull_request.id }}-${{ steps.current-time.outputs.now }} | md5sum | head -c 16 | awk '{ print $1 }')" >> $GITHUB_OUTPUT

    - name: 🗑️ Delete and Backup Previous deployment to Server
      id: backup-and-delete
      uses: appleboy/ssh-action@v1.0.0
      env:
        DEPLOY_PATH: ${{ inputs.deploy-path }}
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        key: ${{ inputs.key }}
        passphrase: ${{ inputs.passphrase }}
        port: ${{ inputs.port }}
        envs: DEPLOY_PATH
        script_stop: true
        script: |
          mkdir -p ~/temp-backup-${{ steps.generate-md5-hash.outputs.md5-hash }}
          mv ~/$DEPLOY_PATH/* ~/temp-backup-${{ steps.generate-md5-hash.outputs.md5-hash }}/
          rm -rf ~/$DEPLOY_PATH/*

    - name: 📀 Deploy build to Server
      id: deploy
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        key: ${{ inputs.key }}
        passphrase: ${{ inputs.passphrase  }}
        port: ${{ inputs.port }}
        source: ${{ inputs.source }}
        target: ${{ inputs.deploy-path }}
        overwrite: true

    - name: 🧹 Cleanup deployment to Server
      id: cleanup
      uses: appleboy/ssh-action@v1.0.0
      env:
        DEPLOY_PATH: ${{ inputs.deploy-path }}
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        key: ${{ inputs.key }}
        passphrase: ${{ inputs.passphrase  }}
        port: ${{ inputs.port }}
        envs: DEPLOY_PATH
        script_stop: true
        script: |
          cd ~/$DEPLOY_PATH
          mv ~/$DEPLOY_PATH/dist/* ~/$DEPLOY_PATH/
          rm -rf ~/$DEPLOY_PATH/dist
          rm -rf ~/temp-backup-${{ steps.generate-md5-hash.outputs.md5-hash }}

    - name: 🧻 RollBack to previous Deployment to Server
      if: steps.deploy.outcome == 'failure' || steps.cleanup.outcome == 'failure' || steps.backup-and-delete.outcome == 'failure'
      uses: appleboy/ssh-action@v1.0.0
      env:
        DEPLOY_PATH: ${{ inputs.deploy-path }}
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        key: ${{ inputs.key }}
        passphrase: ${{ inputs.passphrase  }}
        port: ${{ inputs.port }}
        envs: DEPLOY_PATH
        script_stop: true
        script: |
          mv ~/temp-backup-${{ steps.generate-md5-hash.outputs.md5-hash }}/* ~/$DEPLOY_PATH/
          rm -rf ~/temp-backup-${{ steps.generate-md5-hash.outputs.md5-hash }}
